name: "Terraform GitHub Actions - Apply"
on:
  pull_request_review_comment:
    types: [edited]
env:
  tf_version: "latest"
  tf_working_dir: "./build"
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          args: 'plan.tfplan'
        env:
          TF_VAR_do_token: "do_token"
          TF_VAR_ssh_fingerprint: "ssh_fingerprint"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
