name: "Terraform GitHub Actions"
on:
  - pull_request
env:
  tf_version: "latest"
  tf_working_dir: "./build"
  actions_version: "0.12.13"
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.actions_version }}
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.actions_version }}
          tf_actions_subcommand: "init"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.actions_version }}
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.actions_version }}
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          args: "-out plan.tfplan"
        env:
          TF_VAR_do_token: "do_token"
          TF_VAR_ssh_fingerprint: "ssh_fingerprint"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: "Terraform Apply"
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: ${{ env.actions_version }}
      #     tf_actions_subcommand: "apply"
      #     tf_actions_working_dir: ${{ env.tf_working_dir }}
      #     tf_actions_comment: true
      #     args: "plan.tfplan"
      #   if: github.event.action != 'closed'
      #   env:
      #     DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      #     # TF_VAR_ssh_fingerprint: "ssh_fingerprint"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
